name: Create issues from todos

on:
  push:
    branches:
      - dev
      - dev-tests

jobs:
    build:
        runs-on: "ubuntu-latest"
        steps:
            - uses: "actions/checkout@v3"
            - name: "TODO to Issue"
              uses: "alstr/todo-to-issue-action@master"